spring:
  profiles:
    active:
      - local

---
spring:
  profiles: local
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/sys-eureka/eureka/





