spring:
  application:
    name: busi-provider-config
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8004

mybatis:
  config-location: classpath:com/xpl/framework/config/spring-mybatis.xml
  mapper-locations: classpath:com/xpl/dao/mapper/*.xml

info:
  name: ${spring.application.name}
  port: ${server.port}
  summary: spring cloud privoder config demo
  auther: xpl
