spring:
  application:
    name: sys-hystrix
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880
  profiles:
    active:

server:
  servlet:
    context-path: /${spring.application.name}
  port: 7002


