spring:
  application:
    name: sys-ribbon
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880
  profiles:
    active:
      - local

server:
  servlet:
    context-path: /${spring.application.name}
  port: 7003


